/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#000000",
        "primary-container": "#c583ff",
        "tertiary-fixed": "#ff87da",
        "primary": "#ce96ff",
        "on-secondary-fixed-variant": "#00586d",
        "secondary-fixed": "#7edeff",
        "surface-container-low": "#131318",
        "on-primary": "#48007a",
        "on-background": "#f8f5fd",
        "outline": "#76747b",
        "on-primary-container": "#37005f",
        "primary-dim": "#a041f0",
        "surface-container-high": "#1f1f26",
        "error": "#ff6e84",
        "secondary-container": "#00677f",
        "on-tertiary": "#430036",
        "inverse-primary": "#8922d8",
        "tertiary": "#ff5ed6",
        "on-tertiary-fixed": "#34002a",
        "on-error-container": "#ffb2b9",
        "tertiary-container": "#ff00d4",
        "inverse-on-surface": "#55545a",
        "secondary-dim": "#00c3ed",
        "background": "#0e0e13",
        "tertiary-dim": "#ff5ed6",
        "on-secondary": "#004253",
        "secondary-fixed-dim": "#30d4ff",
        "secondary": "#00d2ff",
        "primary-fixed": "#c583ff",
        "on-surface": "#f8f5fd",
        "surface-bright": "#2c2b33",
        "primary-fixed-dim": "#bc6fff",
        "surface-variant": "#25252c",
        "on-primary-fixed": "#000000",
        "surface-dim": "#0e0e13",
        "error-dim": "#d73357",
        "on-secondary-fixed": "#003a48",
        "surface-tint": "#ce96ff",
        "outline-variant": "#48474d",
        "on-tertiary-fixed-variant": "#6f005b",
        "on-primary-fixed-variant": "#450074",
        "surface-container-highest": "#25252c",
        "error-container": "#a70138",
        "tertiary-fixed-dim": "#ff6bd7",
        "surface-container": "#19191f",
        "on-secondary-container": "#eefaff",
        "inverse-surface": "#fbf8ff",
        "surface": "#0e0e13",
        "on-tertiary-container": "#0e000a",
        "on-error": "#490013",
        "on-surface-variant": "#acaab1",
      },
      fontFamily: {
        headline: ["var(--font-epilogue)", "Epilogue", "sans-serif"],
        body: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        label: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        "neon-purple": "0 0 20px rgba(206, 150, 255, 0.3)",
        "neon-cyan": "0 0 20px rgba(0, 210, 255, 0.3)",
        "neon-pink": "0 0 20px rgba(255, 94, 214, 0.3)",
        "glow-purple": "0 20px 40px -10px rgba(206, 150, 255, 0.4)",
        "glow-cyan": "0 20px 40px -10px rgba(0, 210, 255, 0.3)",
        "header": "0 40px 40px -5px rgba(206, 150, 255, 0.12)",
        "nav": "0 -10px 30px -10px rgba(0, 210, 255, 0.2)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.5s ease-out",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(206, 150, 255, 0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(206, 150, 255, 0.6)" },
        },
      },
    },
  },
  plugins: [],
};
