/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#fcf9f8",
        "outline-variant": "#484847",
        "inverse-on-surface": "#565555",
        "on-surface": "#ffffff",
        "inverse-primary": "#9900d1",
        "primary-fixed": "#d779ff",
        "primary-dim": "#b90afc",
        "on-secondary-fixed-variant": "#9f0059",
        "background": "#0e0e0e",
        "tertiary-container": "#2ff801",
        "surface-tint": "#de8eff",
        "surface-dim": "#0e0e0e",
        "primary-container": "#d779ff",
        "tertiary": "#8eff71",
        "tertiary-dim": "#2be800",
        "on-error-container": "#ffb2b9",
        "on-tertiary": "#0d6100",
        "outline": "#767575",
        "error": "#ff6e84",
        "tertiary-fixed-dim": "#2be800",
        "on-tertiary-fixed-variant": "#0d6200",
        "surface-container-low": "#131313",
        "secondary-fixed-dim": "#ffacc8",
        "primary": "#de8eff",
        "secondary-dim": "#e10080",
        "secondary-container": "#b90068",
        "on-tertiary-container": "#0b5800",
        "surface-bright": "#2c2c2c",
        "surface": "#0e0e0e",
        "on-primary-fixed-variant": "#4b0069",
        "tertiary-fixed": "#2ff801",
        "on-secondary": "#460024",
        "surface-container-highest": "#262626",
        "secondary": "#ff68a7",
        "on-secondary-container": "#fff5f6",
        "secondary-fixed": "#ffc1d4",
        "surface-container-lowest": "#000000",
        "on-tertiary-fixed": "#064200",
        "error-container": "#a70138",
        "on-error": "#490013",
        "on-primary-fixed": "#000000",
        "on-background": "#ffffff",
        "on-secondary-fixed": "#6b003a",
        "surface-container": "#1a1a1a",
        "on-primary": "#4f006e",
        "on-primary-container": "#3d0056",
        "surface-variant": "#262626",
        "surface-container-high": "#20201f",
        "on-surface-variant": "#adaaaa",
        "primary-fixed-dim": "#cf62ff",
        "error-dim": "#d73357"
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
